// Run against a local preview: npm run preview -- --host 127.0.0.1
// BROWSER_EXECUTABLE optionally selects an existing Chrome installation.
import assert from 'node:assert/strict';
import fs from 'node:fs';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = process.env.DEMO_URL || 'http://127.0.0.1:4173/';
const browser = await chromium.launch({ headless: true, executablePath: process.env.BROWSER_EXECUTABLE || undefined, args: ['--disable-gpu'] });
const context = await browser.newContext({ viewport: { width: 1280, height: 900 }, serviceWorkers: 'block' });
const errors = []; const firebaseRequests = [];
const page = await context.newPage();
page.on('pageerror', error => errors.push(error.message));
page.on('request', request => { if (/firestore|firebase|identitytoolkit|securetoken/.test(request.url())) firebaseRequests.push(request.url()); });
await page.route('**/*', route => new URL(route.request().url()).origin === new URL(base).origin ? route.continue() : route.abort());
try {
  await page.goto(base);
  await page.getByRole('button', { name: 'Community Feed', exact: true }).click();
  const feed = JSON.parse(fs.readFileSync('public/activity.json', 'utf8'));
  await page.locator('article').first().waitFor();
  assert.equal(await page.locator('article').count(), feed.posts.length, 'renders the current source JSON contract');
  await page.getByRole('button', { name: 'Profile & League', exact: true }).click();
  await page.getByRole('button', { name: 'Return as Alex A' }).click();
  await page.getByLabel('Spotsy tag (optional)').fill('3');
  await page.getByLabel('Request ace-pot entry').check();
  await page.getByRole('button', { name: 'Check in for sample league', exact: true }).click();
  assert.match(await page.getByRole('status').textContent(), /awaits staff confirmation/);
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('spotsy-members-demo-v1')).payments.length), 0);
  await page.reload();
  await page.getByRole('button', { name: 'Profile & League', exact: true }).click();
  await page.getByRole('button', { name: 'Check in for sample league', exact: true }).click();
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('spotsy-members-demo-v1')).attendance.length), 1);
  fs.mkdirSync('docs/screenshots', { recursive: true });
  await page.screenshot({ path: 'docs/screenshots/member-desktop.png' });
  await page.getByRole('button', { name: 'Casual Rounds', exact: true }).click();
  await page.getByRole('button', { name: 'Join Card', exact: true }).click();
  await page.getByRole('button', { name: 'Leave Card', exact: true }).waitFor();
  await page.getByPlaceholder('Coordinate parking or tee times...').fill('Synthetic coordination: meet at the practice basket.');
  await page.locator('form').getByRole('button').click();
  await page.getByText('Synthetic coordination: meet at the practice basket.', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Leave Card', exact: true }).click();
  await page.getByText('Join this casual round to access card chat & tee time updates.').waitFor();
  await page.getByRole('button', { name: 'Organize a Round', exact: true }).click();
  await page.locator('input[type="date"]').fill('2026-10-15');
  await page.locator('input[type="time"]').fill('10:00');
  await page.locator('form').getByRole('button', { name: /Post|Create/ }).click();
  await page.getByText('Alex River', { exact: true }).first().waitFor();
  await page.getByRole('button', { name: 'Mark Completed', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: 'Closed card — read only', exact: true }).isDisabled(), true);
  await page.reload();
  await page.getByRole('button', { name: 'Casual Rounds', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: 'Closed card — read only', exact: true }).isDisabled(), true);
  await page.getByRole('button', { name: 'Organize a Round', exact: true }).click();
  await page.locator('input[type="date"]').fill('2026-10-16');
  await page.locator('input[type="time"]').fill('10:00');
  await page.locator('form').getByRole('button', { name: /Post|Create/ }).click();
  await page.getByRole('button', { name: 'Cancel Round', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: 'Closed card — read only', exact: true }).count(), 2);
  for (const button of await page.getByRole('button', { name: 'Closed card — read only', exact: true }).all()) assert.equal(await button.isDisabled(), true);
  await page.getByText('Chat closed because this round is completed.', { exact: true }).waitFor();
  await page.getByText('Chat closed because this round is cancelled.', { exact: true }).waitFor();
  const closedStatuses = await page.evaluate(() => Object.entries(JSON.parse(localStorage.getItem('spotsy-demo-documents-v1'))).filter(([key, value]) => key.startsWith('rounds/') && value.organizerId === 'demo-user-uid-202').map(([, value]) => value.status).sort());
  assert.deepEqual(closedStatuses, ['cancelled', 'completed']);
  await page.locator('aside nav').getByRole('button', { name: /^Club Ops/ }).click();
  await page.getByRole('button', { name: 'Enter organizer demo', exact: true }).click();
  await page.getByRole('button', { name: /Load synthetic roster/ }).click();
  const memberSelector = page.getByLabel('Existing member (IDs distinguish identical names)');
  await memberSelector.selectOption('sample-alex-b');
  assert.equal(await page.getByLabel('Division', { exact: true }).inputValue(), 'MA3');
  assert.equal(await page.getByLabel('Spotsy tag (optional)').inputValue(), '2');
  assert.equal(await page.getByLabel('Stafford tag (optional)').inputValue(), '101');
  await page.getByRole('button', { name: 'Check in for sample league', exact: true }).click();
  await page.getByLabel('Spotsy tag (optional)').fill('99');
  await memberSelector.selectOption('sample-alex-a');
  assert.equal(await page.getByLabel('Division', { exact: true }).inputValue(), 'MA4');
  assert.equal(await page.getByLabel('Spotsy tag (optional)').inputValue(), '1');
  assert.equal(await page.getByLabel('Stafford tag (optional)').inputValue(), '');
  await page.getByLabel('Confirm ace pot for sample-alex-a', { exact: true }).check();
  assert.equal(await page.evaluate(() => {
    const state = JSON.parse(localStorage.getItem('spotsy-members-demo-v1'));
    const id = state.attendance.find(a => a.memberId === 'sample-alex-a').id;
    return state.payments.find(p => p.attendanceId === id).aceConfirmed;
  }), true);
  await page.getByRole('button', { name: 'Build Cards', exact: true }).click();
  const finalize = page.getByRole('button', { name: 'Finalize for 6:00', exact: true });
  assert.equal(await finalize.isEnabled(), true);
  await finalize.click();
  await page.getByText('6:00 PM shotgun call-out order', { exact: true }).waitFor();
  await page.getByText('Card Builder', { exact: true }).evaluate(element => element.scrollIntoView({ block: 'start' }));
  await page.screenshot({ path: 'docs/screenshots/organizer-cards-desktop.png' });
  await page.getByLabel('Upload UDisc XLSX').setInputFiles('tests/fixtures/synthetic-udisc.xlsx');
  await page.getByRole('button', { name: 'Save reviewed import', exact: true }).waitFor();
  await page.waitForFunction(() => [...document.querySelectorAll('button')].some(b => b.textContent === 'Save reviewed import' && !b.disabled));
  await page.getByText('UDisc XLSX reconciliation', { exact: true }).evaluate(element => element.scrollIntoView({ block: 'start' }));
  await page.screenshot({ path: 'docs/screenshots/organizer-reconciliation-desktop.png' });
  await page.getByRole('button', { name: 'Save reviewed import', exact: true }).click();
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('spotsy-members-demo-v1')).results.length), 11);
  await page.getByRole('button', { name: 'Save reviewed import', exact: true }).click();
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('spotsy-members-demo-v1')).imports.length), 1);
  await page.getByText('Bag-tag handoff preview', { exact: true }).evaluate(element => element.scrollIntoView({ block: 'start' }));
  await page.screenshot({ path: 'docs/screenshots/organizer-import-desktop.png' });
  await page.getByRole('button', { name: 'Reopen check-in', exact: true }).click();
  const evidence = await page.evaluate(() => { const s = JSON.parse(localStorage.getItem('spotsy-members-demo-v1')); return { results: s.results, imports: s.imports }; });
  await page.getByLabel('Confirm ace pot for sample-alex-a', { exact: true }).uncheck();
  await memberSelector.selectOption('sample-alex-a');
  await page.getByRole('button', { name: 'Check in for sample league', exact: true }).click();
  assert.deepEqual(await page.evaluate(() => { const s = JSON.parse(localStorage.getItem('spotsy-members-demo-v1')); return { results: s.results, imports: s.imports }; }), evidence);
  assert.equal(await page.getByText('Bag-tag handoff preview', { exact: true }).count(), 1);
  await page.getByText(/Alex River \(sample-alex-a\):.*payment not confirmed/).waitFor();
  await page.getByLabel('Spotsy tag (optional)').fill('88');
  await page.getByLabel('Guest name').fill('Guest Nova');
  await page.getByRole('button', { name: 'Create guest record', exact: true }).click();
  assert.equal(await page.getByLabel('Guest name').inputValue(), '', 'guest intake fields reset for the next walk-up');
  assert.equal(await page.getByLabel('Division', { exact: true }).inputValue(), 'MA4');
  assert.equal(await page.getByLabel('Spotsy tag (optional)').inputValue(), '');
  assert.equal(await page.getByLabel('Stafford tag (optional)').inputValue(), '');
  assert.equal(await page.getByLabel('Request ace-pot entry').isChecked(), false);
  await page.getByRole('button', { name: 'Check in for sample league', exact: true }).click();
  assert.deepEqual(await page.evaluate(() => { const s = JSON.parse(localStorage.getItem('spotsy-members-demo-v1')); return { results: s.results, imports: s.imports }; }), evidence);
  await page.getByText('Attendance changed.', { exact: false }).waitFor();
  assert.equal(await page.getByText('Bag-tag handoff preview', { exact: true }).count(), 0);
  const guestId = await page.evaluate(() => JSON.parse(localStorage.getItem('spotsy-members-demo-v1')).members.find(m => m.name === 'Guest Nova').id);
  await page.getByRole('button', { name: 'Profile & League', exact: true }).click();
  await page.getByRole('button', { name: 'New member setup', exact: true }).click();
  await page.locator('select').last().selectOption(guestId);
  await page.getByRole('button', { name: 'Request review', exact: true }).click();
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('spotsy-members-demo-v1')).claims[0].status), 'pending');
  await page.locator('aside nav').getByRole('button', { name: /^Club Ops/ }).click();
  await page.getByRole('button', { name: 'Enter organizer demo', exact: true }).click();
  await page.getByRole('button', { name: 'Approve reviewed claim', exact: true }).click();
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('spotsy-members-demo-v1')).identities.find(i => i.authId === 'demo-new-member').memberId), guestId);
  await page.getByRole('button', { name: 'Create Club Event', exact: true }).click();
  await page.getByPlaceholder('e.g., Thursday Night League').fill('Synthetic adoption event');
  await page.getByPlaceholder('Check-in, fees, divisions, format, or other current details...').fill('Fictional event for local quicklink verification.');
  await page.getByPlaceholder('https://example.com/udisc/sample-event').fill('https://example.com/udisc/verified-sample');
  await page.getByRole('button', { name: 'Add Demo Event', exact: true }).click();
  await page.locator('aside nav').getByRole('button', { name: 'Events', exact: true }).click();
  await page.getByRole('heading', { name: 'Synthetic adoption event', exact: true }).waitFor();
  assert.equal(await page.locator('a[href="https://example.com/udisc/verified-sample"]').count(), 1);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(base + '?leagueCheckIn=sample-thursday');
  await page.getByRole('button', { name: 'New member setup', exact: true }).click();
  await page.getByLabel('Display name').fill('Guest Nova');
  await page.getByRole('button', { name: 'Save profile once', exact: true }).click();
  await page.getByRole('button', { name: 'Check in for sample league', exact: true }).click();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'mobile screen fits viewport');
  await page.screenshot({ path: 'docs/screenshots/member-mobile.png', fullPage: true });
  assert.deepEqual(errors, []); assert.deepEqual(firebaseRequests, []);
  console.log('PASS: current source feed, member return, stable repeat attendance, casual round join/chat/leave/create, completed/cancelled card guards, selected-member hydration and fresh guest defaults, staff payment confirmation, organizer cards, actual XLSX import/repeat, evidence preserved after payment/repeat check-in, changed-roster review, guest claim review, event quicklink, mobile layout, no Firebase requests or page errors. Service workers blocked; offline/PWA acceptance unverified.');
} finally { await browser.close(); }
